analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.655427
  lightness: 0.345394
  rhythmicContrast: 0.719646
  saturation: 0.26412
cta: {}
layout_spectrum: 0.398848
name: theguides
opengraph: {}
purpose: {}
typography_spectrum: 0.407072
